language: python
cache: pip
sudo: false
services:
  - redis-server

# Test environments
matrix:
  include:
  #  - env: TOXENV=py34
  #    python: 3.4
  #  - env: TOXENV=py35
  #    python: 3.5
   - env: TOXENV=py36
     python: 3.6

# Package installation
install:
  - pip3 install tox codecov
  - pip3 install -r requirements.txt
  - pip3 install -e .[dev]
  - python3 setup.py develop

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - pytest
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - pytest

# Register code coverage in coveralls
after_success:
  codecov
