# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20171003_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.SmallIntegerField(choices=[(0, 'Integer'), (1, 'Float'), (2, 'String'), (3, 'URL')]),
        ),
    ]
